micronaut:
  application:
    name: keyManager

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}/${DATABASE:pixgrpc}
    username: ${DATABASE_USERNAME:pixgrpc}
    password: ${DATABASE_PASSWORD:pixgrpc}
    driver-class-name: org.postgresql.Driver
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        hbm2ddl:
          auto: update

itau:
  contas:
    url: 'http://localhost:9091'

bcb:
  pix:
    url: ${URL_BCB_PIX:'http://localhost:8082'}